spring:
  application:
    name: rental_service
  datasource:
      url: jdbc:mysql://localhost:3306/rentaldb
      username: root
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

aws:
  region: us-east-2
  sns:
    livro-alugado-topic-arn: "arn:aws:sns:us-east-2:${AWS_ACCOUNT_ID}:livro-alugado-topic"
    livro-lembrete-topic-arn: "arn:aws:sns:us-east-2:${AWS_ACCOUNT_ID}:livro-lembrete-topic"
    livro-retornado-topic-arn: "arn:aws:sns:us-east-2:${AWS_ACCOUNT_ID}:livro-retornado-topic"
  sqs:
    livro-criado-queue: livro-criado-queue
    livro-atualizado-queue: livro-atualizado-queue

server:
  port: 8081
