spring:
  application:
    name: notification_service
  data:
    mongodb:
      uri: mongodb://localhost:27017/notificationdb
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

aws:
  region: us-east-2
  sqs:
    livro-alugado-queue: livro-alugado-queue
    livro-lembrete-queue: livro-lembrete-queue
    livro-retornado-queue: livro-retornado-queue

server:
  port: 8082
